spring.application.name=server
spring.config.import=optional:file:.env[.properties]


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_LOCAL_USER}
spring.datasource.password=${DB_LOCAL_PASSWORD}


application.security.jwt.secret-key=${JWT_SECRET_KEY}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR